name: Build and Deploy Code

on: [push, pull]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Hello welcome to my repository
        run: echo "Hello welcome to my repository"